#ifndef CSKIA_H
#define CSKIA_H

/* Umbrella header for the SkiaSharp C API. The headers include each other relative to
   the Skia source root, so the "include/c/" prefix is part of the layout. */

#include "include/c/gr_context.h"
#include "include/c/sk_bitmap.h"
#include "include/c/sk_blender.h"
#include "include/c/sk_canvas.h"
#include "include/c/sk_codec.h"
#include "include/c/sk_colorfilter.h"
#include "include/c/sk_colorspace.h"
#include "include/c/sk_data.h"
#include "include/c/sk_document.h"
#include "include/c/sk_drawable.h"
#include "include/c/sk_font.h"
#include "include/c/sk_general.h"
#include "include/c/sk_graphics.h"
#include "include/c/sk_graphite.h"
#include "include/c/sk_graphite_dawn.h"
#include "include/c/sk_graphite_metal.h"
#include "include/c/sk_graphite_vulkan.h"
#include "include/c/sk_image.h"
#include "include/c/sk_imagefilter.h"
#include "include/c/sk_linker.h"
#include "include/c/sk_maskfilter.h"
#include "include/c/sk_matrix.h"
#include "include/c/sk_paint.h"
#include "include/c/sk_path.h"
#include "include/c/sk_pathbuilder.h"
#include "include/c/sk_patheffect.h"
#include "include/c/sk_picture.h"
#include "include/c/sk_pixmap.h"
#include "include/c/sk_region.h"
#include "include/c/sk_rrect.h"
#include "include/c/sk_runtimeeffect.h"
#include "include/c/sk_shader.h"
#include "include/c/sk_stream.h"
#include "include/c/sk_string.h"
#include "include/c/sk_surface.h"
#include "include/c/sk_svg.h"
#include "include/c/sk_textblob.h"
#include "include/c/sk_typeface.h"
#include "include/c/sk_types.h"
#include "include/c/sk_vertices.h"
#include "include/c/skottie_animation.h"
#include "include/c/skresources_resource_provider.h"
#include "include/c/sksg_invalidation_controller.h"

#endif /* CSKIA_H */
